services:
  rail-data-downloader:
    build:
      context: ./
    environment:
      RAIL_DATA_USERNAME : "YOUR_USERNAME"
      RAIL_DATA_PASSWORD : "YOUR_PASSWORD"
    volumes:
      - ./src:/app

networks:
  default:
    name: hadoop-net