services:
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./prefect_flows:/opt/prefect/prefect_flows
      - ../ingestion/:/opt/prefect/ingestion
      - ../transformation.zip:/opt/prefect/spark_apps/transformation.zip
      - ../transformation:/opt/prefect/spark_apps/transformation
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./requirements.txt:/opt/prefect/requirements.txt
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
      PATH: /opt/spark/bin:$PATH
      PYSPARK_PYTHON: python3
    command: prefect worker start --pool local-pool
  
  prefect-client:
      image: prefecthq/prefect:3-latest
      environment:
        PREFECT_API_URL: http://prefect-server:4200/api
      volumes:
        - ./prefect_configurations:/opt/prefect/configurations
        - ./prefect_flows:/opt/prefect/prefect_flows
      entrypoint: "bash"

networks:
  default:
    name: hadoop-net