services:
  prefect-worker:
    image: prefecthq/prefect:3-latest
    volumes:
      - ./prefect_flows:/opt/prefect/flows
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    command: prefect worker start --pool local-pool
  
  prefect-client:
      image: prefecthq/prefect:3-latest
      environment:
        PREFECT_API_URL: http://prefect-server:4200/api
      volumes:
        - ./prefect_configurations:/opt/prefect/configurations
      entrypoint: "bash"

networks:
  default:
    name: hadoop-net