services:
  prefect-worker:
    image: prefecthq/prefect:3-latest
    volumes:
      - ./prefect_flows:/opt/prefect/prefect_flows
      - ./requirements.txt:/opt/prefect/requirements.txt
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    command: >
      bash -c "pip install -r requirements.txt 
      && prefect worker start --pool local-pool"
  
  prefect-client:
      image: prefecthq/prefect:3-latest
      environment:
        PREFECT_API_URL: http://prefect-server:4200/api
      volumes:
        - ./prefect_configurations:/opt/prefect/configurations
        - ./prefect_flows:/opt/prefect/prefect_flows
      entrypoint: "bash"

networks:
  default:
    name: hadoop-net