services:
  jupyter:
    image: quay.io/jupyter/pyspark-notebook:spark-3.4.0
    ports:
      - 8888:8888
    volumes:
      - ./jupyter_data:/home/jovyan/jupyter_data
    command: "start-notebook.sh --NotebookApp.token="

networks:
  default:
    name: hadoop-net