include:
  - compose.cluster.yml
services:
  hive-metastore:
    image: apache/hive:4.0.1
    platform: linux/arm64
    hostname: metastore
    ports:
      - 9083:9083
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password
    volumes:
      - ./configuration/hive/drivers/postgresql-42.7.5.jar:/opt/hive/lib/postgresql-42.6.0.jar
    depends_on:
      - hive-metastore-db

  hive-metastore-db:
    image: postgres:15.10
    platform: linux/arm/v5
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./hive/metastore-db-data:/var/lib/postgresql/data      
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=hive
      - POSTGRES_DB=metastore_db

      
  hive-server:
    image: apache/hive:4.0.1
    platform: linux/arm64
    hostname: hiveserver2
    ports:
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - namenode
      - datanode-1
      - datanode-2
      - hive-metastore
    environment:
      - SERVICE_NAME=hiveserver2
      - IS_RESUME=true
      - HADOOP_CONF_DIR=/opt/hadoop/conf
    volumes:
      - ./configuration/hadoop:/opt/hadoop/conf
      - ./configuration/hive/hive-site.xml:/opt/hive/conf/hive-site.xml

networks:
  default:
    name: hadoop-net