services:
  jupyter:
    image: quay.io/jupyter/pyspark-notebook:spark-3.5.3
    ports:
      - 8888:8888
    volumes:
      - ./jupyter_data:/home/jovyan/jupyter_data
      - ../1-sample-data-platform/transformation:/home/jovyan/transformation
    command: "start-notebook.sh --NotebookApp.token="

networks:
  default:
    name: hadoop-net