services:
  namenode:
    image: hadoop:3.4.2-java17    
    hostname: hdfs-namenode
    ports: 
        - "9870:9870"
        - "8088:8088"
    command: > 
      bash -c "hdfs namenode & yarn resourcemanager"
    volumes:
     - ./namenode-data:/data/dfs/data/

  datanode-1:
    image: hadoop:3.4.2-java17
    hostname: datanode1
    depends_on: 
        - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager"
    ports:
      - "9864:9864"
      - "8042:8042"
    links:
        - namenode:hdfs-namenode

  datanode-2:
    image: hadoop:3.4.2-java17
    hostname: datanode2
    depends_on: 
        - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager "
    ports:
      - "9865:9864"
      - "8043:8042"
    links:
        - namenode:hdfs-namenode


networks:
  default:
    name: hadoop-net