services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    hostname: hdfs-namenode
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "2gb"
    ports: 
        - "9870:9870"
        - "8088:8088"
    command: > 
      bash -c "hdfs namenode & yarn resourcemanager & sleep 20 && source /init_tez.sh && tail -f /dev/null"
    volumes:
     - ./namenode-data:/data/dfs/data/
     - ./configuration/hadoop/yarn-site.xml:/usr/local/hadoop/etc/hadoop/yarn-site.xml
     - ./configuration/tez/tez-site.xml:/usr/local/tez/conf/tez-site.xml

  datanode-1:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    hostname: datanode1
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2gb"
    depends_on: 
        - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager"
    ports:
      - "9864:9864"
      - "8042:8042"
    volumes:
     - ./configuration/hadoop/yarn-site.xml:/usr/local/hadoop/etc/hadoop/yarn-site.xml
     - ./configuration/tez/tez-site.xml:/usr/local/tez/conf/tez-site.xml
    links:
        - namenode:hdfs-namenode

  datanode-2:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    hostname: datanode2
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2gb"
    depends_on: 
        - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager"
    ports:
      - "9865:9864"
      - "8043:8042"
    volumes:
     - ./configuration/hadoop/yarn-site.xml:/usr/local/hadoop/etc/hadoop/yarn-site.xml
     - ./configuration/tez/tez-site.xml:/usr/local/tez/conf/tez-site.xml
    links:
        - namenode:hdfs-namenode
  
  datanode-3:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    hostname: datanode3
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2gb"
    depends_on: 
        - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager"
    ports:
      - "9866:9864"
      - "8044:8042"
    volumes:
     - ./configuration/hadoop/yarn-site.xml:/usr/local/hadoop/etc/hadoop/yarn-site.xml
     - ./configuration/tez/tez-site.xml:/usr/local/tez/conf/tez-site.xml
    links:
        - namenode:hdfs-namenode


networks:
  default:
    name: hadoop-net