FROM apache/superset:5.0.0

USER root

ENV SUPERSET_CONFIG_PATH /app/superset_config.py

RUN . /app/.venv/bin/activate && \
    uv pip install psycopg2-binary pyhive thrift thrift_sasl

USER superset

ENTRYPOINT ["/bin/bash", "-c", "\
    superset db upgrade && \
    superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin && \
    superset init && \
    . /app/docker/entrypoints/run-server.sh \
"]